# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: SendErrorToDiscord

on:
  schedule:
    - cron: '20,50 * * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  log:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Send Discord message
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: deno run start
